[MUI-414], [MUI-415] Asset name table component
minterest-finance/ui-kit pull request #3
Opened 2022-07-08 11:00 UTC by p1geon

# Description

Please include a summary of the change in short form.

## Jira ticket(optional)

[414](https://minterestfinance.atlassian.net/browse/MUI-414)
[415](https://minterestfinance.atlassian.net/browse/MUI-415)

## Type of change

Please pick options that are relevant.

- [ ] Bug fix OR refactoring (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature or refactoring that would cause existing functionality to not work as expected)
![image](https://user-images.githubusercontent.com/14223261/177979616-59e46df5-9ee5-433b-b8e1-7de4c6e38d07.png)

2022-07-11 13:42 UTC, gavrilin-remote requested changes

2022-07-11 13:42 UTC, gavrilin-remote commented on src/components/Table/AssetName/AssetName.tsx
> +import { AssetIconBlank, AssetNameLoading } from 'assets/svg';
remove unused icons, replace loader issets with react-content-loader

2022-07-12 09:09 UTC, p1geon commented on src/components/Table/AssetName/AssetName.tsx
> +import { AssetIconBlank, AssetNameLoading } from 'assets/svg';
fixed

2022-07-12 09:11 UTC, p1geon commented on src/components/Table/AssetName/AssetName.tsx
> +import { AssetIconBlank, AssetNameLoading } from 'assets/svg';
fixed

2022-07-12 09:12 UTC, p1geon commented on src/components/Table/AssetName/AssetName.tsx
> +  <AssetNameLoading {...props} />
fixed

2022-07-13 14:30 UTC, gavrilin-remote commented on src/components/Table/AssetName/AssetName.tsx
> +  fontWeight: 700,
why here 700??? in figma 600, use table1 typography variant

2022-07-14 09:07 UTC, p1geon commented on src/stories/Table/AssetName.stories.tsx
> +      options: ['BTCIcon', 'DAIIcon', 'USDCIcon', 'USDTIcon', 'WETHIcon'],
removed extra icons

2022-07-14 09:08 UTC, p1geon commented on src/components/Table/AssetName/AssetName.tsx
> +  fontWeight: 700,
they are different in different places in Figma. Checking which one should be applied

2022-07-14 10:57 UTC, p1geon commented on src/components/Table/AssetName/AssetName.tsx
> +  fontWeight: 700,
600 is correct. Figma has been updated accordingly

2022-07-14 11:35 UTC, mr-teddy-bear approved these changes

2022-07-15 07:58 UTC, marinakulsha approved these changes

2022-07-18 10:54 UTC, merged