[MUI-380]: Update design of banner message
minterest-finance/ui-kit pull request #4
Opened 2022-07-11 20:33 UTC by mr-teddy-bear

# Description

Code review for banner message component

## Jira ticket(optional)

[MUI-380](https://minterestfinance.atlassian.net/jira/software/projects/MUI/boards/7?assignee=62591503eee0a9006ab98b74&selectedIssue=MUI-380)

## Type of change

Please pick options that are relevant.

- [ ] Bug fix OR refactoring (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature or refactoring that would cause existing functionality to not work as expected)

2022-07-13 14:23 UTC, gavrilin-remote commented on src/components/HeaderMessage/HeaderMessage.tsx
> +  background: theme.palette.custom.light,
not sure we should use custom here, but ok

2022-07-13 14:24 UTC, gavrilin-remote commented on src/components/HeaderMessage/HeaderMessage.tsx
> +  background: theme.palette.custom.light,
I will replace it later

2022-07-13 14:26 UTC, gavrilin-remote requested changes

2022-07-13 14:26 UTC, gavrilin-remote commented on src/components/HeaderMessage/HeaderMessage.tsx
> +const Description = styled('div')(({ theme }) => ({
replace div with Typography

2022-07-13 14:26 UTC, gavrilin-remote commented on src/components/HeaderMessage/HeaderMessage.tsx
> +const Description = styled('div')(({ theme }) => ({
and use proper variant, we already have such font
`fontFamily: 'Open Sans',
  fontStyle: 'normal',
  fontWeight: 400,`

2022-07-13 19:05 UTC, mr-teddy-bear commented on src/components/HeaderMessage/HeaderMessage.tsx
> +const Description = styled('div')(({ theme }) => ({
Done, but something wrong after merging with main -_-
Linter hate me)

2022-07-14 11:34 UTC, gavrilin-remote approved these changes

2022-07-15 07:37 UTC, BerRossDolmat approved these changes

2022-07-15 07:38 UTC, marinakulsha approved these changes

2022-07-15 07:39 UTC, BerRossDolmat commented on src/components/HeaderMessage/HeaderMessage.tsx
> +  maxWidth: '729px',
magic number for width, not cool in ui kit that can be used in different layout

2022-07-15 07:39 UTC, BerRossDolmat commented on src/theme.ts
>        // example todo remove later
needs to be removed?

2022-07-15 07:40 UTC, BerRossDolmat commented on src/components/HeaderMessage/HeaderMessage.tsx
> +  width: '1226px',
magic number in width

2022-07-25 11:48 UTC, merged