[MUI-605]: Connect wallet for tablet
minterest-finance/ui-kit pull request #42
Opened 2022-10-03 19:51 UTC by mr-teddy-bear

# Description

Connect wallet for tablet

## Jira ticket(optional)

[MUI-605](https://minterestfinance.atlassian.net/jira/software/projects/MUI/boards/7?assignee=62591503eee0a9006ab98b74&selectedIssue=MUI-605)

## Type of change

Please pick options that are relevant.

- [ ] Bug fix OR refactoring (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature or refactoring that would cause existing functionality to not work as expected)

2022-10-05 07:26 UTC, BerRossDolmat approved these changes

2022-10-05 07:49 UTC, l-polina approved these changes

2022-10-05 12:26 UTC, gavrilin-remote requested changes

2022-10-05 12:26 UTC, gavrilin-remote commented on src/components/Navigation/Drawer.tsx
> +    display: 'none',
I don't like that way to hide button. This is highly unexpected.

2022-10-05 12:26 UTC, gavrilin-remote commented on src/components/Navigation/Drawer.tsx
> +    display: 'none',
Better do not pass it from main-frontend and keep ui-kit component as much clear as we can

2022-10-05 15:00 UTC, BerRossDolmat commented on src/components/Navigation/Drawer.tsx
> +    display: 'none',
From one side, this components is not to be reused, probably. From other side, would be good to have this configurable from a place of use.
So probably some prop can be passed with failsafe default here?

2022-10-12 07:31 UTC, gavrilin-remote requested changes

2022-10-12 07:31 UTC, gavrilin-remote commented on src/components/Navigation/Drawer.tsx
> +  hideExtraComponentOnTablet,
I think will be better to pass props like showExtraComponent and control this from main-frontend

2022-10-12 07:31 UTC, gavrilin-remote commented on src/components/Navigation/Drawer.tsx
> +        <BottomButton hideExtraComponentOnTablet={hideExtraComponentOnTablet}>
```suggestion
        {ExtraComponent && showExtraComponent && <BottomButton><ExtraComponent /></BottomButton>}
```

2022-10-12 21:30 UTC, mr-teddy-bear commented on src/components/Navigation/Drawer.tsx
> +  hideExtraComponentOnTablet,
Done

2022-10-12 21:30 UTC, mr-teddy-bear commented on src/components/Navigation/Drawer.tsx
> +        <BottomButton hideExtraComponentOnTablet={hideExtraComponentOnTablet}>
Done

2022-10-12 21:44 UTC, mr-teddy-bear commented on src/components/Navigation/Drawer.tsx
> +    display: 'none',
Done

2022-10-17 10:54 UTC, merged