[MUI-383]: Stats wing component
minterest-finance/ui-kit pull request #5
Opened 2022-07-11 22:43 UTC by mr-teddy-bear

# Description

Update the design of Your Stats Wing - Desktop

## Jira ticket(optional)

[MUI-383](https://minterestfinance.atlassian.net/jira/software/projects/MUI/boards/7?assignee=62591503eee0a9006ab98b74&selectedIssue=MUI-383)

## Type of change

Please pick options that are relevant.

- [ ] Bug fix OR refactoring (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature or refactoring that would cause existing functionality to not work as expected)

2022-07-14 08:08 UTC, p1geon commented on src/components/StatsWing/StatsWing.tsx
> +export const Shimmer = styled('div')<{
I think we should be using react-content-loader instead

2022-07-14 08:18 UTC, p1geon requested changes
- The circle looks slightly 'squared out' on the edges
![image](https://user-images.githubusercontent.com/14223261/178935751-8a27fa70-3e83-43fc-a401-22e9349d47ca.png)

- Tooltip icon is missing then the whole Wing Thing is in connected state
![image](https://user-images.githubusercontent.com/14223261/178935894-5911e62c-252a-43e5-91e8-b974027ba2e1.png)

- When the component is disconnected, the circle should be a different color
<img width="183" alt="image" src="https://user-images.githubusercontent.com/14223261/178936111-eaf15aa6-128a-454e-8e92-5a381c18ec83.png">

2022-07-14 08:32 UTC, DmytroMinterest approved these changes

2022-07-14 11:13 UTC, mr-teddy-bear commented on src/components/StatsWing/StatsWing.tsx
> +export const Shimmer = styled('div')<{
Done

2022-07-14 11:14 UTC, mr-teddy-bear commented on src/stories/StatsWing.stories.tsx
> +export const Header: ComponentStory<typeof StatsWing> = (args) => (
Done

2022-07-14 12:09 UTC, p1geon commented on src/components/StatsWing/StatsWing.tsx
> +          }
This hurts to look at xD I understand that this is correct from design perspective, but because of the loader gradient it is painful to watch. I would suggest not setting up the background, but I don't know who should decide that.

2022-07-19 07:01 UTC, slavaminterest approved these changes

2022-07-19 07:55 UTC, mr-teddy-bear commented on src/components/StatsWing/StatsWing.tsx
> +          }
done

2022-07-19 07:58 UTC, p1geon approved these changes

2022-07-28 07:45 UTC, closed without merging